name: on_your_table_waiter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  go_router: ^5.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  font_awesome_flutter: ^10.3.0
  intl: ^0.17.0
  riverpod: ^2.1.1
  uuid: ^3.0.7
  collection: ^1.16.0
  oyt_front_core:
    path: ./packages/oyt_front_core
  oyt_front_widgets:
    path: ./packages/oyt_front_widgets
  oyt_front_auth:
    path: ./packages/oyt_front_auth
  hive_flutter: ^1.1.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.1.0

flutter:
  uses-material-design: true
