name: on_your_table_waiter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  go_router: ^5.1.1
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  socket_io_client: ^2.0.0
  dartz: ^0.10.1
  font_awesome_flutter: ^10.2.1
  mobile_scanner: ^2.0.0
  lottie: ^1.4.3
  intl: ^0.17.0
  riverpod: ^2.0.2
  uuid: ^3.0.6
  hive: ^2.2.3
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
